config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
#  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get 'login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
            format: { with: VALID_EMAIL_REGEX}, 
            uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  # Returns the hash digest for the given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   include ApplicationHelper
   include SessionsHelper
   protect_from_forgery with: :exception

   def hello
	   render html: "hello world"
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else 
      #create an error  message
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @g_image = "G_logo.png"
  end

  def help
  end
  
  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Language Lab!"
      redirect_to @user
    else 
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else 
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please Log In."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper 
  #logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    user && user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirect to stored locaion or the default
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		The Grinnell Language Laboratory by Carol Yan.
	</small>
	<nav>
		<ul>
			<li><%= link_to "About",   about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Language Lab", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home",   root_path %></li>
				<li><%= link_to "Help",   help_path %></li>
				<li><%= link_to "Sign Up", signup_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log Out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
		  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
		  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all',
			'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= render 'layouts/shim'%>
	</head>
	<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>In this project, I practiced the traditional RESTful APIs to clearly organize the application structure. In the web front end developing aspect, I was able to add images, buttons, navigation bars, and configured consistent aesthetic design. (I put heart and soul into the aesthetic design but from my user tests result, apparently the feedback is mixed.) I am able to separate the header and footer from other static and non-static components of the website. Additionally, I was able to implement user models. The website is now functional as the user can sign up, log in. In the sign up process, the website can check inputs validity. For example, REGEX was applied here to check email address the user typed in. Also, to authenticate the user trying to log in, the website can check the database for users’ input. I also used cookie to store the user information so that one can be automatically logged in before the cookie is lost. The part I am most proud of is the selective display of contents and check of authority access. As shown in the code snippet in question 1, I was able to check if the user is logged in before allowing the users to see some of the contents such as user index, and to change the user profiles. I also wrote extensive tests to cover most of the major features of my projects, and I believe this is quite an essential part in software development. </p>
<p>
The Alternate Language Study Option (ALSO) program is a self-instructional/peer-tutored language learning program designed for highly self-motivated and disciplined students who want to learn a language not taught through the regular curriculum at Grinnell. The program provides a two-semester sequence of beginning level study in several languages, including but not limited to Italian, Portuguese, Korean, Hindi, and Kiswahili. The specific languages offered depend on the number of students interested and the availability of trained peer tutors.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>ALSO program department contact information: </p>
<p>patchkat@grinnell.edu</p>
<p>Phone (641) 269-4740</p>
<p>Fax (641) 269-4985</p>
<br>
<p>Website technical problem contact information</p>
<p>yancarolfake@grinnell.edu</p>
<p>phone (002) 515-51515</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
      <h1>Help</h1>
      <p>  
        Get help on the Ruby on Rails Tutorial at the
        <a href="https://www.railstutorial.org/help">Rails Tutorial help section</a>.
	To get help on this sample app, see the
	<a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
    book</a>.</br>
  If you require additional academic help, please contact Chinese Department at Grinnell College or your Chinese professor. Chinese Labs are held Sunday through Thursday 8-10 pm and could be another source if you require assistance. 
  If you require additional technical help, please contact Carol Yan (yanxinyi@grinnell.edu) or ITS if the issue is urgent.
  
      </p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Grinnell Language Lab</h1>

  <%= image_tag("G_logo.png", :alt => "Grinnell logo feed", :size => "260x250", :align => "middle")%>
  <br><br>
  <div class="btn-group", style:{padding-top: 25px;}>
    <%= link_to "Tutee Log In", login_path, class: "btn btn-lg btn-primary", :align => "middle" %>
    <%= link_to "Tutor Log In", login_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "Professor Log In", login_path, class: "btn btn-lg btn-primary" %>
  </div>
  <p>Chinese Labs are organized by Chinese department at Grinnell College Alternate Language Study Option (ALSO). Grinnell College owns the final explaination of all events.</p>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= will_paginate%>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password , class: 'form-control'%>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation , class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>
<h2 class="tutee_summary"> Progress Summary: 2/12</h2>
<table id="display_tutee_history" align="center">
  <tr>
    <th>Date</th>
    <th>Topic</th>
    <th>Comment</th>
  </tr>
  <tr>
    <td>Jan 13</td>
    <td>Worked on dictation</td>
    <td>Have good understanding of the unit vocabulary</td>
  </tr>
  <tr>
    <td>Feb 22</td>
    <td>Worked on essay</td>
    <td>Need to work on grammar</td>
  </tr>
</table>